env:
  es6: true
  node: true
extends:
  - airbnb-base
  - plugin:@typescript-eslint/recommended
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 2018
  sourceType: module
plugins:
  - '@typescript-eslint'
  - 'eslint-plugin-prettier'
settings:
  import/resolver:
    node:
      extensions:
        - .ts
rules:
  linebreak-style: ['error', 'windows']
  no-console: 'off'
  semi: 'off'
  operator-linebreak: 'off'
  max-len: ['off']
  import/extensions: ['error', 'ignorePackages', {
    'ts': 'never',
  }]
  arrow-parens: 'off'
  '@typescript-eslint/member-delimiter-style': 'off'
  prettier/prettier:
    - error
    - printWidth: 130
      tabWidth: 2
      semi: false
      singleQuote: true
      jsxSingleQuote: false
      trailingComma: all
      bracketSpacing: true
      jsxBracketSameLine: false
      arrowParens: avoid
      proseWrap: preserve
      htmlWhitespaceSensitivity: css
      endOfLine: auto